# -*- coding: utf-8 -*-
"""conditional_logic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aAm-ziYhVs-GlNyGfcc1PjtdJPDW4HMQ
"""

bool(0)

bool(-1)
bool(1)

bool(1)

bool(100)

True

False

type(True)

bool(True)

bool(0)

bool(-1)

bool(100)

bool(100*0)

bool(0.00000000)

bool(0.0000000001)

bool(' ')

bool('string')

bool('')

bool([1,2,3])

bool([1])

bool([])

a=True
b=False

a and b

a or b

li=[1,2,3]

4 in li

3 in li

str=['a','b','c','d','e']

'f' in str

'e'in str

a=5
b=-3
c=0
a,b,c

if a>0:
  print('a is positive')

if b>0:
  print('b is positive')

if c==0:
  print('zero')

if b<0:
  print('b is negative')



""">, <. ==, <==, >==, !== can be used as well"""

a>=b

a<=b

a<b

a!=b

if b<0:
  print('b is neg')
else:
  print('b is not ne')

if a<0:
  print('a neg')
else:
  print('a not neg')

if c==0:
  print('zero')
elif c>0:
  print('positive')
else:
  print('neg')

vowels=['a','e','i','o', 'u']

x='i'
if x in vowels:
  print('vowel')
else:
  print('consonent')

x='y'
if x in vowels:
  print('vowel')
else:
  print('consonent')

