# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GzhXDfQx5HNc5e44tLC8Xf0wSiwgFR_R
"""

li=['lamp','laptop', 'cell phone', 'pen', 'stapler']

li

type(li)

len(li)

li[0]

li[1]

li[-1]

li[-2]

li[0:3]

li[1:3]

li[-1:]

li[0:-1]

li[0:4]

li[0:4:2]

li[0:4:1]

li[::1]

li[::2]

li[::-1]

li=li+['pencil']

li

li[3]='Pen'

li

li[3]=li[3]+"holder"

li



li