# -*- coding: utf-8 -*-
"""string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XuKKc04x7WzTALNBMBzCBL1C6zJcgXF6
"""

type("Bangladesh")

type('Bangladesh')

Country="Bangladesh"
print(Country)

str="adam\'s new shoe"
print(str)

Country[0]

Country[1]

Country[-1]

len(Country)

Country[10]

Country[0]='b'
print(Country)

a='Bangla'
b='desh'
c=a+b
print(c)

c.find('Bangla')

c.find('Baj')

c.replace('desh','link',-1)

print(c)

str=' b c d '
str.strip()

str.lstrip()

str.rstrip()

str='AbcdEf'
str.upper()

str.lower()

str1='bangla'
str2='desh'
str1,str2

"""for swap

"""

str1,str2=str2,str1
print(str1)

temp=str1
str1=str2
str2=temp
print(str1)

txt = "Hello World" [::-1]
print(txt)

